config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'products#index'

  resources :products, only: [:show, :index] do
    collection do
      get 'search'
    end
  end


  resources :categories, only: [:show]

  resource :cart, only: [:show, :destroy] do
    collection do
      get 'checkout'
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete 'cancel'
      post 'pay'
      get 'pay_confirm'
    end
    collection do
      get 'confirm'
    end
  end

 
  namespace :admin do
    root 'products#index'
    resources :products, exctpt: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put 'sort'
      end
    end
    resources :subscribes, only: [:index, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
      post 'cart', to: 'utils#cart'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/frontend/_carousel.html.erb
<div id="carousel" class="carousel">
  <% show_products.each do |product| %>
    <div class="item">
      <%= link_to product_path(product) do %>
        <% if product.cover_image.attached? %>  
          <%= image_tag product.cover_image.variant(resize_to_fill: [500  , 500]) %>
        <% else %>
          <%= image_tag 'https://fakeimg.pl/500x500/?text=NO cover' %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="footer has-background-white">
  <section class="container">
    <div class="columns">
      <div class="column">
        <div class="menu">
          <p class="menu-label">關於我們</p>
          <ul class="menu-list">
            <li><a>關於 citiesocial</a></li>
            <li><a>隱私權保護政策</a></li>
            <li><a>服務條款</a></li>
          </ul>   
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">聯絡我們</p>
          <ul class="menu-list">
            <li><a>02.2393.2610</a></li>
            <li><a>業務合作洽談</a></li>
          </ul>   
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">自助查詢</p>
          <ul class="menu-list">
            <li><a>銀行優惠說明</a></li>
            <li><a>LINE Points 回饋說明</a></li>
          </ul>   
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">顧客服務</p>
          <ul class="menu-list">
            <li><a>VIEWS生活誌</a></li>
            <li><a>會員回饋計畫</a></li>
            <li><a>退換貨說明</a></li>
            <li><a>客服中心</a></li>
          </ul>   
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_pack_tag 'citiesocial_logo.png' %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= form_tag search_products_path, method: :get, class: 'questions-search-form'  do %>
        <div class="navbar-item field has-addons">
          <div class="control">
            <input class="form-control input" name="query_string" type="text" placeholder="輸入關鍵字">
          </div>
          <div class="control">
            <button type="submit" class="button is-primary">
              <i class="fas fa-search"></i>&nbsp; 搜尋
            </button>
          </div>
        </div>
      <% end %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <div class="navbar-item" data-controller="cart">
            <%= link_to cart_path do %>
              <i class="fas fa-shopping-cart"></i>
              <span data-target="cart.count" data-action="addToCartEvent@document->cart#updateCart">
                (<%= current_cart.items.count %>)
              </span>
            <% end %>
          </div>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <i class="fas fa-user"></i>&nbsp;<%= current_user.email %>
            </a>
            <div class="navbar-dropdown">
              <%= link_to "個人資料", edit_user_registration_path, class:'navbar-item' %>
              <%= link_to "訂單紀錄", orders_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to "後台管理", admin_root_path, class: 'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to "登出", destroy_user_session_path, method:'delete', data: {confirm: '確認登出?!' }, class:'navbar-item' %>
            </div>
          </div>
        <% else %>
          <div class="buttons">
            <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "登入", new_user_session_path, class: 'button is-light' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/frontend/_product_list.html.erb
<section class="product_list section">
  <section class="container">
    <h1 class="title"><%= title ||= "" %></h1>
    <div class="columns is-multiline">
      <% if products.empty? %>
        <div class="content">
          <h4 class="is-size-4">找不到商品</h4>
        </div>
      <% else %>
        <% products.each do |product| %>
          <div class="column is-3">
            <div class="card product-item is-shadowless">
              <div class="card-image">
                <figure class="image">
                  <%= link_to product_path(product) do  %>
                    <% if product.cover_image.attached? %>  
                      <%= image_tag product.cover_image.variant(resize_to_fill: [400, 400]) %>
                    <% else %>
                      <%= image_tag 'https://fakeimg.pl/400x400/?text=cover_image' %>
                    <% end %>
                  <% end %>
                </figure>
              </div>
              <div class="card-content">
                <div class="content">
                  <h4 class="is-size-6"><%= product.vendor.title %></h4>
                  <p><%= link_to product.name, product, class: 'has-text-dark' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

app/views/shared/frontend/_subscribe.html.erb
<section class="subscribe section has-background-light is-centered has-text-centered" data-controller="subscribe">
  <h3 class="has-text-centered is size-4">訂閱電子報</h3>

  <div class="containar">
    <form actiono="#">
      <div class="field has-addons">
        <div class="control has-icons-left is-expanded">
          <input type="email"  data-target="subscribe.email" placeholder="請輸入你的 Email 信箱" name="email" class="input is-rounded">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
        <div class="control">
          <input type="submit" value="訂閱電子報", class="button is-primary is-rounded" data-action="subscribe#add">
        </div>
      </div>
    </form>
  </div>
</section>

app/views/shared/frontend/_top-menu.html.erb
<div class="tabs is-centered">
  <ul>
    <% @categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
    <%  end %>
  </ul>
</div>