config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'products#index'

  resources :products, only: [:show, :index] do
    collection do
      get 'search'
    end
  end


  resources :categories, only: [:show]

  resource :cart, only: [:show, :destroy] do
    collection do
      get 'checkout'
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete 'cancel'
      post 'pay'
      get 'pay_confirm'
    end
    collection do
      get 'confirm'
    end
  end

 
  namespace :admin do
    root 'products#index'
    resources :products, exctpt: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put 'sort'
      end
    end
    resources :subscribes, only: [:index, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
      post 'cart', to: 'utils#cart'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/backend/_navbar.html.erb
<nav class="navbar has-shadow is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to admin_root_path, class: 'navbar-item' do %>
      <i class="fas fa-home"></i>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "商品", admin_products_path, class: 'navbar-item' %>
      <%= link_to "廠商", admin_vendors_path, class: 'navbar-item' %>
      <%= link_to "分類", admin_categories_path, class: 'navbar-item' %>
      <%= link_to "訂閱電子報", admin_subscribes_path, class: 'navbar-item' %>      
    </div>
    
    <div class="navbar-end">
      <%= link_to "返回前台", root_path, class: 'navbar-item' %>
    </div>
  </div>
</nav>