config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'products#index'

  resources :products, only: [:show, :index] do
    collection do
      get 'search'
    end
  end


  resources :categories, only: [:show]

  resource :cart, only: [:show, :destroy] do
    collection do
      get 'checkout'
    end
  end

  resources :orders, except: [:new, :edit, :update, :destroy] do
    member do
      delete 'cancel'
      post 'pay'
      get 'pay_confirm'
    end
    collection do
      get 'confirm'
    end
  end

 
  namespace :admin do
    root 'products#index'
    resources :products, exctpt: [:show]
    resources :vendors, except: [:show]
    resources :categories, except: [:show] do
      collection do
        put 'sort'
      end
    end
    resources :subscribes, only: [:index, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post 'subscribe', to: 'utils#subscribe'
      post 'cart', to: 'utils#cart'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart
  attr_reader :items
  def initialize( hash =[])
    @items = hash
  end

  def self.form_hash( hash = nil )
    if hash && hash["items"]
      items = hash["items"].map { |item| 
        CartItem.new(item["sku_id"], item["quantity"])
      }
      cart = Cart.new(items)
    else
      Cart.new
    end
  end

  def add_sku (sku_id, quantity = 1 )
    found = @items.find { |item| item.sku_id == sku_id }
    if found 
      found.increment!(quantity)
    else
      @items << CartItem.new(sku_id, quantity)
    end
  end
  
  def total_price
    @items.reduce(0) { |sum, item| sum + item.total_price }
    #記得reduce(0) 要給初始值,不然會拿陣列中第一個物件當初始值
  end

  def to_serialize
    items = @items.map { |item| { "sku_id" => item.sku_id, 
                                "quantity" => item.quantity}}
    { "items" => items}
  end

  def empty?
    @items.empty?
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def destroy
    session[:cart_9527] = nil
    redirect_to root_path, notice: '購物車已清空'
  end

  def checkout
    @order = current_user.orders.build  #以使用者的角度去新增一張訂單
  end

end

app/views/carts/_cart.html.erb
<% if current_cart.empty? %>
你的購物車是空的!</br>
<%= link_to "繼續購物", root_path, class: 'button is-medium' %>
<% else %>
<table class="table is-fullwidth">
  <thead>
    <th>品項</th>
    <th>單價</th>
    <th>數量</th>
    <th>狀態</th>
    <th>  </th>
  </thead>
  <tbody>
    <% current_cart.items.each do |item| %>
      <tr>
        <th><%= item.product.name %></th>
        <th><%= item.product.sell_price %></th>
        <th><%= item.quantity %></th>
        <th><%= item.total_price %></th>
    <% end %>
  </tbody>
</table>
<%= link_to "繼續購物", root_path, class: 'button is-medium' %>
<%= link_to "前往結帳", checkout_cart_path, class: 'button is-danger is-medium' %>
<% end %>

app/views/carts/checkout.html.erb
<section class="section">
  <h1 class="title"">結帳</h1>
  <%= render 'cart' %>
  
  <hr>
  
  <h2 class="title is-size-5">收件人資訊</h2>
  <%= form_with(model: @order) do |form| %>
    <div class="columns">
      <div class="column">
        <div class="field">
          <%= form.label :recipient, "收信人", class: 'label' %>
          <%= form.text_field :recipient, class: 'input is-medium' %>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :tel, "電話", class: 'label' %>
          <%= form.text_field :tel, class: 'input is-medium' %>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <%= form.label :address, "地址", class: 'label' %>
          <%= form.text_field :address, class: 'input is-medium' %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= form.label :note, "備註說明", class: 'label' %>        
      <%= form.text_area :note, class: "textarea is-medium" %>
    </div>
    <div class="field">
      <%= form.submit '使用 Line Pay 結帳', class: 'button is-primary is-medium', data: { confirm: '確認送出?'} %>
    </div>
  <% end %>
  </section>

app/views/carts/show.html.erb
<section class="section">
  <h1 class="title"">購物車
    <%= link_to cart_path, method: 'delete', data: { confirm: "確定要清空購物車嗎?"}, class: 'is-size-5' do %>
      <i class="far fa-trash-alt"></i>
      <span>清空購物車</span>
    <% end %>
  </h1>
  <%= render 'cart' %>
</section>